# Sylius AssortmentBundle
sylius_assortment:
  driver: doctrine/orm
  classes:
    product:
      model: Ibrows\SyliusShopBundle\Entity\Product
      controller: Ibrows\SyliusShopBundle\Controller\ProductController
      repository: Ibrows\SyliusShopBundle\Repository\ProductRepository
      form: Ibrows\SyliusShopBundle\Form\Type\ProductType
    variant:
      model: Ibrows\SyliusShopBundle\Entity\Variant
      form: Ibrows\SyliusShopBundle\Form\Type\VariantType