sylius_inventory:
  driver: doctrine/orm
  backorders: false
  classes:
      unit:
          model: Ibrows\SyliusShopBundle\Entity\InventoryUnit
      stockable:
          model: sylius_inventory.classes.stockable.model 