sylius_inventory:
    driver: doctrine/orm
    backorders: false
    classes:
        unit:
            model: %ibrows_sylius_shop.inventory.class%
        stockable:
            model: %ibrows_sylius_shop.product.class%