jms_payment_core:
    secret: 'WK{Q?j)JHG>!p:hkvaJ3'
jms_payment_paypal:
    username: your api username (not your account username)
    password: your api password (not your account password)
    signature: your api signature
    debug: true